name: Fetch Data

on:
    push:
        branches:
            - main
    schedule:
        # every night at 01:30 UTC
      - cron:  "30 1 * * *"

jobs:
    get_data:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Fetch monthly data
                run: python -m src monthly

            -   name: Archive data
                uses: actions/upload-artifact@v4
                with:
                    name: monthly_all_stations.csv
                    path: data/monthly_all_stations.csv
