name: Fetch Data

on:
    push:
        branches:
            - main
    schedule:
        # every morning at 06:30 UTC
      - cron:  "30 15 * * *"

jobs:
    get_data:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Fetch monthly data
                run: python -m src daily

            -   name: Archive data
                uses: actions/upload-artifact@v4
                with:
                    name: daily_weather_data
                    path: data/daily_all_stations.csv
